import Head from "next/head";
import Header from "./components/Header";
import Image from "next/image";
import Link from "next/link";
import ActiveLink from "./components/ActiveLink";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BetterMind Counseling Collective</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
}
